language: ruby

sudo: false

cache:
  bundler: true

rvm:
  - 2.3

install:
  - bundle install --retry=3

script:
  - bundle exec rake

env:
  - "RAILS_VERSION=5.0"
  - "RAILS_VERSION=master"

addons:
  code_climate:
    repo_token: 059801d3b65779b50b46b2e58b4f683339615ec1e428f03acec04b21954ad365

matrix:
  allow_failures:
    - rvm: ruby-head
    - env: "RAILS_VERSION=master"
  fast_finish: true
